language: node_js
node_js:
  - "0.10"
env:
  global:
    - secure: "QVKuNy9o+aP4a7mKGZDIQknbS3Xwwd5p4Lp2jWYjm8A6QSDczYN0xBbOtI+4f3ZVP3pl1rlv1nDz5Qnw3H9n02P9vrtgmcGv0xayKCUxqKqsTGxN4sCJO4VKmRKm1fOW7DlXKi2TxhloJLo1Jp/95zqsoZ7U9O9cvxGSFNKd32E="
script:
  - npm run travis
after_success:
  - $(npm bin)/coveralls < ./coverage/lcov.info
